# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/antoine/EPITECH/indieStudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/antoine/EPITECH/indieStudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/cpack --config ./CPackSourceConfig.cmake /home/antoine/EPITECH/indieStudio/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/antoine/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antoine/EPITECH/indieStudio/CMakeFiles /home/antoine/EPITECH/indieStudio/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antoine/EPITECH/indieStudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw_objlib

# Build rule for target.
glfw_objlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw_objlib
.PHONY : glfw_objlib

# fast build rule for target.
glfw_objlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw_objlib.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw_objlib.dir/build
.PHONY : glfw_objlib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Main.cpp.s
.PHONY : Main.cpp.s

src/Object/AObject.o: src/Object/AObject.cpp.o

.PHONY : src/Object/AObject.o

# target to build an object file
src/Object/AObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/AObject.cpp.o
.PHONY : src/Object/AObject.cpp.o

src/Object/AObject.i: src/Object/AObject.cpp.i

.PHONY : src/Object/AObject.i

# target to preprocess a source file
src/Object/AObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/AObject.cpp.i
.PHONY : src/Object/AObject.cpp.i

src/Object/AObject.s: src/Object/AObject.cpp.s

.PHONY : src/Object/AObject.s

# target to generate assembly for a file
src/Object/AObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/AObject.cpp.s
.PHONY : src/Object/AObject.cpp.s

src/Object/Collisionable/CollisionableObject.o: src/Object/Collisionable/CollisionableObject.cpp.o

.PHONY : src/Object/Collisionable/CollisionableObject.o

# target to build an object file
src/Object/Collisionable/CollisionableObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/CollisionableObject.cpp.o
.PHONY : src/Object/Collisionable/CollisionableObject.cpp.o

src/Object/Collisionable/CollisionableObject.i: src/Object/Collisionable/CollisionableObject.cpp.i

.PHONY : src/Object/Collisionable/CollisionableObject.i

# target to preprocess a source file
src/Object/Collisionable/CollisionableObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/CollisionableObject.cpp.i
.PHONY : src/Object/Collisionable/CollisionableObject.cpp.i

src/Object/Collisionable/CollisionableObject.s: src/Object/Collisionable/CollisionableObject.cpp.s

.PHONY : src/Object/Collisionable/CollisionableObject.s

# target to generate assembly for a file
src/Object/Collisionable/CollisionableObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/CollisionableObject.cpp.s
.PHONY : src/Object/Collisionable/CollisionableObject.cpp.s

src/Object/Collisionable/Destructible/DestructibleObject.o: src/Object/Collisionable/Destructible/DestructibleObject.cpp.o

.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.o

# target to build an object file
src/Object/Collisionable/Destructible/DestructibleObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleObject.cpp.o
.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.cpp.o

src/Object/Collisionable/Destructible/DestructibleObject.i: src/Object/Collisionable/Destructible/DestructibleObject.cpp.i

.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/DestructibleObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleObject.cpp.i
.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.cpp.i

src/Object/Collisionable/Destructible/DestructibleObject.s: src/Object/Collisionable/Destructible/DestructibleObject.cpp.s

.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/DestructibleObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleObject.cpp.s
.PHONY : src/Object/Collisionable/Destructible/DestructibleObject.cpp.s

src/Object/Collisionable/Destructible/DestructibleWall.o: src/Object/Collisionable/Destructible/DestructibleWall.cpp.o

.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.o

# target to build an object file
src/Object/Collisionable/Destructible/DestructibleWall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleWall.cpp.o
.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.cpp.o

src/Object/Collisionable/Destructible/DestructibleWall.i: src/Object/Collisionable/Destructible/DestructibleWall.cpp.i

.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/DestructibleWall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleWall.cpp.i
.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.cpp.i

src/Object/Collisionable/Destructible/DestructibleWall.s: src/Object/Collisionable/Destructible/DestructibleWall.cpp.s

.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/DestructibleWall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/DestructibleWall.cpp.s
.PHONY : src/Object/Collisionable/Destructible/DestructibleWall.cpp.s

src/Object/Collisionable/Destructible/Movable/Bullet.o: src/Object/Collisionable/Destructible/Movable/Bullet.cpp.o

.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.o

# target to build an object file
src/Object/Collisionable/Destructible/Movable/Bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Bullet.cpp.o
.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.cpp.o

src/Object/Collisionable/Destructible/Movable/Bullet.i: src/Object/Collisionable/Destructible/Movable/Bullet.cpp.i

.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/Movable/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Bullet.cpp.i
.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.cpp.i

src/Object/Collisionable/Destructible/Movable/Bullet.s: src/Object/Collisionable/Destructible/Movable/Bullet.cpp.s

.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/Movable/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Bullet.cpp.s
.PHONY : src/Object/Collisionable/Destructible/Movable/Bullet.cpp.s

src/Object/Collisionable/Destructible/Movable/Cannon.o: src/Object/Collisionable/Destructible/Movable/Cannon.cpp.o

.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.o

# target to build an object file
src/Object/Collisionable/Destructible/Movable/Cannon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Cannon.cpp.o
.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.cpp.o

src/Object/Collisionable/Destructible/Movable/Cannon.i: src/Object/Collisionable/Destructible/Movable/Cannon.cpp.i

.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/Movable/Cannon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Cannon.cpp.i
.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.cpp.i

src/Object/Collisionable/Destructible/Movable/Cannon.s: src/Object/Collisionable/Destructible/Movable/Cannon.cpp.s

.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/Movable/Cannon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Cannon.cpp.s
.PHONY : src/Object/Collisionable/Destructible/Movable/Cannon.cpp.s

src/Object/Collisionable/Destructible/Movable/MovableObject.o: src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.o

.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.o

# target to build an object file
src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.o
.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.o

src/Object/Collisionable/Destructible/Movable/MovableObject.i: src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.i

.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.i
.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.i

src/Object/Collisionable/Destructible/Movable/MovableObject.s: src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.s

.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.s
.PHONY : src/Object/Collisionable/Destructible/Movable/MovableObject.cpp.s

src/Object/Collisionable/Destructible/Movable/Tank.o: src/Object/Collisionable/Destructible/Movable/Tank.cpp.o

.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.o

# target to build an object file
src/Object/Collisionable/Destructible/Movable/Tank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Tank.cpp.o
.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.cpp.o

src/Object/Collisionable/Destructible/Movable/Tank.i: src/Object/Collisionable/Destructible/Movable/Tank.cpp.i

.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.i

# target to preprocess a source file
src/Object/Collisionable/Destructible/Movable/Tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Tank.cpp.i
.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.cpp.i

src/Object/Collisionable/Destructible/Movable/Tank.s: src/Object/Collisionable/Destructible/Movable/Tank.cpp.s

.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.s

# target to generate assembly for a file
src/Object/Collisionable/Destructible/Movable/Tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Destructible/Movable/Tank.cpp.s
.PHONY : src/Object/Collisionable/Destructible/Movable/Tank.cpp.s

src/Object/Collisionable/Wall.o: src/Object/Collisionable/Wall.cpp.o

.PHONY : src/Object/Collisionable/Wall.o

# target to build an object file
src/Object/Collisionable/Wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Wall.cpp.o
.PHONY : src/Object/Collisionable/Wall.cpp.o

src/Object/Collisionable/Wall.i: src/Object/Collisionable/Wall.cpp.i

.PHONY : src/Object/Collisionable/Wall.i

# target to preprocess a source file
src/Object/Collisionable/Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Wall.cpp.i
.PHONY : src/Object/Collisionable/Wall.cpp.i

src/Object/Collisionable/Wall.s: src/Object/Collisionable/Wall.cpp.s

.PHONY : src/Object/Collisionable/Wall.s

# target to generate assembly for a file
src/Object/Collisionable/Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Object/Collisionable/Wall.cpp.s
.PHONY : src/Object/Collisionable/Wall.cpp.s

src/Raylib/Raylib.o: src/Raylib/Raylib.cpp.o

.PHONY : src/Raylib/Raylib.o

# target to build an object file
src/Raylib/Raylib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Raylib/Raylib.cpp.o
.PHONY : src/Raylib/Raylib.cpp.o

src/Raylib/Raylib.i: src/Raylib/Raylib.cpp.i

.PHONY : src/Raylib/Raylib.i

# target to preprocess a source file
src/Raylib/Raylib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Raylib/Raylib.cpp.i
.PHONY : src/Raylib/Raylib.cpp.i

src/Raylib/Raylib.s: src/Raylib/Raylib.cpp.s

.PHONY : src/Raylib/Raylib.s

# target to generate assembly for a file
src/Raylib/Raylib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Raylib/Raylib.cpp.s
.PHONY : src/Raylib/Raylib.cpp.s

src/Scene/AScene.o: src/Scene/AScene.cpp.o

.PHONY : src/Scene/AScene.o

# target to build an object file
src/Scene/AScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Scene/AScene.cpp.o
.PHONY : src/Scene/AScene.cpp.o

src/Scene/AScene.i: src/Scene/AScene.cpp.i

.PHONY : src/Scene/AScene.i

# target to preprocess a source file
src/Scene/AScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Scene/AScene.cpp.i
.PHONY : src/Scene/AScene.cpp.i

src/Scene/AScene.s: src/Scene/AScene.cpp.s

.PHONY : src/Scene/AScene.s

# target to generate assembly for a file
src/Scene/AScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Scene/AScene.cpp.s
.PHONY : src/Scene/AScene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... glfw"
	@echo "... glfw_objlib"
	@echo "... raylib"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... src/Object/AObject.o"
	@echo "... src/Object/AObject.i"
	@echo "... src/Object/AObject.s"
	@echo "... src/Object/Collisionable/CollisionableObject.o"
	@echo "... src/Object/Collisionable/CollisionableObject.i"
	@echo "... src/Object/Collisionable/CollisionableObject.s"
	@echo "... src/Object/Collisionable/Destructible/DestructibleObject.o"
	@echo "... src/Object/Collisionable/Destructible/DestructibleObject.i"
	@echo "... src/Object/Collisionable/Destructible/DestructibleObject.s"
	@echo "... src/Object/Collisionable/Destructible/DestructibleWall.o"
	@echo "... src/Object/Collisionable/Destructible/DestructibleWall.i"
	@echo "... src/Object/Collisionable/Destructible/DestructibleWall.s"
	@echo "... src/Object/Collisionable/Destructible/Movable/Bullet.o"
	@echo "... src/Object/Collisionable/Destructible/Movable/Bullet.i"
	@echo "... src/Object/Collisionable/Destructible/Movable/Bullet.s"
	@echo "... src/Object/Collisionable/Destructible/Movable/Cannon.o"
	@echo "... src/Object/Collisionable/Destructible/Movable/Cannon.i"
	@echo "... src/Object/Collisionable/Destructible/Movable/Cannon.s"
	@echo "... src/Object/Collisionable/Destructible/Movable/MovableObject.o"
	@echo "... src/Object/Collisionable/Destructible/Movable/MovableObject.i"
	@echo "... src/Object/Collisionable/Destructible/Movable/MovableObject.s"
	@echo "... src/Object/Collisionable/Destructible/Movable/Tank.o"
	@echo "... src/Object/Collisionable/Destructible/Movable/Tank.i"
	@echo "... src/Object/Collisionable/Destructible/Movable/Tank.s"
	@echo "... src/Object/Collisionable/Wall.o"
	@echo "... src/Object/Collisionable/Wall.i"
	@echo "... src/Object/Collisionable/Wall.s"
	@echo "... src/Raylib/Raylib.o"
	@echo "... src/Raylib/Raylib.i"
	@echo "... src/Raylib/Raylib.s"
	@echo "... src/Scene/AScene.o"
	@echo "... src/Scene/AScene.i"
	@echo "... src/Scene/AScene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

